name: "Create Pull Request"
on:
  push:
    tags:
      - "v[1-9].*.*"
defaults:
  run:
    shell: bash

jobs:
  build:
    defaults:
      run:
        shell: bash
    name: Build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Remove v from Tag
        id: remove
        run: |
          tag="${{ github.ref_name }}"
          echo "version=${tag//v/}" >> $GITHUB_OUTPUT
      
      - name: Get Branch Name
        id: branch
        run: |
          tag="${{ github.ref_name }}"
          echo "branch_name=${tag%'.'*}" >> $GITHUB_OUTPUT
      

      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ steps.branch.outputs.branch_name }}
      - name: Get bun
        uses: oven-sh/setup-bun@v2 
      
      # - run: ls
      # - run: |
      #     cd site_electron
      #     ls

      
      - name: Prepare and run Bun
        if: ${{ startswith(github.ref_name, 'v') }}
        run: |
          cd site_electron
          bun i
          bun i -D vite-plugin-electron-renderer
          bun run build

  #     - run: ls release
  #     - run: ls release/${{ steps.remove.outputs.version }}

      - name: Archive Windows Installer
        if: ${{ startswith(github.ref_name, 'v') }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            site_electron/release/${{ steps.remove.outputs.version }}/grimoire-nea-Windows-${{ steps.remove.outputs.version }}-Installer.exe
      
      - name: Compress Windows Unpacked
        if: ${{ startswith(github.ref_name, 'v') }}
        run: |
          cd site_electron/release/${{ steps.remove.outputs.version }}
          tar -cvf win-unpacked.tar.gz win-unpacked

      - name: Archive Windows Unpacked
        if: ${{ startswith(github.ref_name, 'v') }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-unpacked
          path: |
            site_electron/release/${{ steps.remove.outputs.version }}/win-unpacked.tar.gz

  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest      
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Remove v from Tag
        id: remove
        run: |
          tag="${{ github.ref_name }}"
          echo "version=${tag//v/}" >> $GITHUB_OUTPUT
      
      - name: Get Branch Name
        id: branch
        run: |
          tag="${{ github.ref_name }}"
          echo "branch_name=${tag%'.'*}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ steps.branch.outputs.branch_name }}
      
      - name: Create Pull Request
        run: |
          gh pr create \
          -B main \
          -H ${{ steps.branch.outputs.branch_name }} \
          -t "Merging of ${{ github.ref_name }} to main" \
          -b "Automatically merging ${{ github.ref_name }} to main"

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      
      - name: Download Windows Installer
        continue-on-error: true
        uses: actions/download-artifact@v5
        with:
          name: windows-installer
          path: artifacts
          
      - name: Download Windows Unpacked
        continue-on-error: true
        uses: actions/download-artifact@v5
        with:
          name: windows-unpacked
          path: artifacts
      
      - run: ls artifacts

      - name: Create Release
        run: |
          gh release create \
          ${{ github.ref_name }} \
          -d \
          -t "Release ${{ github.ref_name }}" \
          -F site_electron/changes.md \
          artifacts/*