name: "Make Release"

on:
  push:
    tags:
    #temporarily 0., will be [1-9].
      - "v0.*.*"

defaults:
  run:
    shell: bash
    #Always run in a development branch

jobs:
  # upload:
  #   defaults:
  #     run:
  #       working-directory: ./site_electron
  #   name: Upload
  #   runs-on: windows-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v7
          # with:
          #   ref: dev
  #     - name: Get bun
  #       uses: oven-sh/setup-bun@v2 

  #     - run: echo ${{ github.ref_type }}
  #     - run: echo ${{ github.ref_name }}

  #     - name: Remove v from Tag
  #       id: remove
  #       run: |
  #         tag="${{ github.ref_name }}"
  #         echo "version=${tag//v/}" >> $GITHUB_OUTPUT

  #     - run: echo ${{ steps.remove.outputs.version }} #TODO FIX THIS
      
  #     - name: Prepare and run Bun
  #       if: startswith(${{ github.ref_name }}, "v")
  #       run: |
  #         bun i
  #         bun i -D vite-plugin-electron-renderer
  #         bun run build

  #     - run: ls release
  #     - run: ls release/${{ steps.remove.outputs.version }}

  #     - name: Archive Windows Installer
  #       if: startswith(${{ github.ref_name }}, "v")
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: windows-installer
  #         path: |
  #           site_electron/release/${{ steps.remove.outputs.version }}/grimoire-nea-Windows-${{ steps.remove.outputs.version }}-Setup.exe
      
  #     - name: Archive Windows Unpacked
  #       if: startswith(${{ github.ref_name }}, "v")
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: windows-unpacked
  #         path: |
  #           release/${{ steps.remove.outputs.version }}/win-unpacked/*
  
  # create-pull-request:
  #   name: Create Pull Request
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #     pull-requests: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v7
  #       with:
  #         ref: dev

  #     - name: Check for git repo
  #       run: |
  #         ls
  #         ls .git
  #     - name: Create Pull Request
  #       if: startswith(${{ github.ref_name }}, "v")
  #       uses: peter-evans/create-pull-request@v8
  #       with:
  #         #temp, dev will be {tag} instead
  #         branch: temp_dev
  #         delete-branch: false
  #         base: main
  #         title: Merging of ${{ github.ref_name }} to main #TODO find out why set permissions dont work

  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest      
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: dev
      
      - name: Create Pull Request
      # dev will need to be changed to current tag
        run: |
          gh pr create -B main -H dev -t "Merging of ${{ github.ref_name }} to main" -b "Automatically merging ${{ github.ref_name }} to main"
  
  # create-release:
  #   name: Create Release
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v7
          # with:
          #   ref: dev
      
  #     - name: Create Release
  #       uses: ncipollo/release-action@v1
  #       with:
  #         artifacts: "README.md"
