name: "Make Release"

on:
  push:
    branches:
      - "main"

defaults:
  run:
    shell: bash
    working-directory: ./site_electron

jobs:
  upload:
    name: "Upload"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Get bun
        uses: oven-sh/setup-bun@v2 
      
      - run: echo "test"
      - run: ls
      - run: bun --version
