name: "Make Release"

on:
  push:
    tags:
    #temporarily 0., will be [1-9].
      - "v0.*.*"

defaults:
  run:
    shell: bash
    #Always run in a development branch
    working-directory: ./site_electron

jobs:
  upload:
    name: "Upload"
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Get bun
        uses: oven-sh/setup-bun@v2 

      - run: echo ${{ github.ref_type }}
      - run: echo ${{ github.ref_name }}
      
      - name: Remove v from Tag
        id: remove
        run: echo "version=${TAG##v}" >> $GITHUB_OUTPUT

      - run: echo ${{ steps.remove.outputs.version }} #TODO FIX THIS
      
      - name: Prepare and run Bun
        if: startswith($TAG, "v")
        run: |
          bun i
          bun i -D vite-plugin-electron-renderer
          bun run build

      # - name: Archive Windows Installer
      #   if: startswith($TAG, "v")
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: windows-installer
      #     path: |
      #       release/${{ github.ref_name }}/grimoire-nea-Windows-${{ github.ref_name }}-Setup.exe
      
      # - name: Archive Windows Unpacked
      #   if: startswith($TAG, "v")
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: windows-unpacked
      #     path: |
      #       release/${{ github.ref_name }}/win-unpacked/*
  
  create-pull-request:
    name: abs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Create Pull Request
        if: startswith(${{ github.ref_name }}, "v")
        uses: peter-evans/create-pull-request@v8
        with:
          branch: dev
          #temp, dev will be {tag} instead
          base: main
